language: objective-c
before_install:
  - sudo easy_install cpp-coveralls
  - brew update
  - brew uninstall xctool # xctool 0.1.4 broken
  - brew install https://raw.github.com/mxcl/homebrew/308395c2fc03399acbc24d226b8558f18e509e5b/Library/Formula/xctool.rb
  - gem update cocoapods
script:
  - xctool test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES