#define kSegueSingleSection @"SingleSection"
#define kSegueMalutSection @"MalutSection"
#define kSegueFectedResult @"FectedResult"
#define kSegueArray @"Array"
#define kReuseCell @"Cell"
#define kReuseAdd @"Add"
#define kSegueEdit @"Edit"
