#define kSegueSingleSection @"SingleSection"
#define kSegueMalutSection @"MalutSection"
#define kSegueFectedResult @"FectedResult"
#define kSegueArray @"Array"
#define kSegueMergeSections @"MergeSections"
#define kReuseCustomTableViewCell @"CustomTableViewCell"
#define kReuseAdd @"Add"
#define kSegueEdit @"Edit"
